### ISSUE TITLE
Bad/old wiki links issue with DuckDuckGo

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms.io#139]
**Submitted on behalf of @pbella (copied from the `LMMS/lmms` repo)**

---

There have been several times when I have searched for 'lmms ' and the top results that come back don't appear to be the most current / relevant for LMMS. Most of these issues have been occurring with DuckDuckGo and when I attempted to replicate via Google, it did not have this issue so it appears to be search engine specific.

For example, when searching for 'lmms piano roll' (without quotes), duckduckgo.com returns the following top 3 links:
https://lmms.io/wiki/index.php?title=Main_Page
http://www.youtube.com/watch?v=7ZHM__Q1bkE
http://lmms.sourceforge.net/wiki/index.php/0.4:Key_Mappings

where performing the same search via Google returns (after redirect):
https://www.youtube.com/watch?v=7ZHM__Q1bkE
https://www.youtube.com/watch?v=4dYxV3tqTUc
https://lmms.io/wiki/index.php?title=Piano_Roll_Editor

The main point here is that the first LMMS 'owned' link in Google results appears to be exactly what someone would expect to be returned, while the first two in DuckDuckGo (wiki home page, old sourceforge wiki) are probably not what one wants. I've tried this type of search with numerous other search terms and it appears to be consistently wrong with DuckDuckGo. Not sure how easy this is to get corrected, but wanted to report it in case there's anything that can be done on the LMMS end...

**Comment by tresf** [comment]
> http://lmms.sourceforge.net/wiki/index.php/0.4:Key_Mappings

Yes, this is a bug.  We should be redirecting to:

**Valid:**
https://lmms.io/wiki/index.php?title=0.4:Key_Mappings

But instead it is probably trying:

**Invalid:**
https://lmms.io/wiki/index.php/0.4:Key_Mappings

Thanks for the information.  There may be other links like this out in the wild.

@Umcaruje  @Lukas-W thoughts appreciated here.  I don't know why some links use one format over the other but if we can either fix our redirects or process the URLs on our side, this could fix some old links from improperly redirecting...

**Comment by badosu** [comment]
@tresf I am a web developer, I'll take a look at this later...

**Comment by Umcaruje** [comment]
>Valid:
https://lmms.io/wiki/index.php?title=0.4:Key_Mappings

>But instead it is probably trying:

>Invalid:
>https://lmms.io/wiki/index.php/0.4:Key_Mappings

But shouldn't it perhaps redirect to 
https://lmms.io/documentation/0.4:Key_Mappings

The wiki is just for editing the articles, we don't link to the wiki from the main page.

**Comment by tresf** [comment]
> The wiki is just for editing the articles, we don't link to the wiki from the main page.

This isn't the main page, this is old search engine links.  I chose to redirect them to `/wiki` to avoid any compat issues with how we mask the URL on our homepage.

So yes, this is desired per our redirect rules.

**Comment by Umcaruje** [comment]
I just searched 'lmms piano roll' over at Duckduckgo and it seems this issue was fixed with their recrawling.

These are the first three results I get: 

![image](https://cloud.githubusercontent.com/assets/6282045/7220051/9faa2f22-e6ba-11e4-8c27-223a51a580fd.png)

They are identical with the results that I get with the same search on google:

![image](https://cloud.githubusercontent.com/assets/6282045/7220052/bd2c3fb8-e6ba-11e4-9815-28c1278d7195.png)

Should this be closed?

**Comment by tresf** [comment]
Well, the issue still remains, so if you close it, we should do "wontfix".  The routing shouldn't be too difficult but we are probably spitting hairs when compared to more important stuff...

**Comment by Umcaruje** [comment]
Closing as a 'wontfix'.
